name: Run Reopen Reports (export)

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Month YYYY-MM (e.g., 2025-08)"
        required: true
        type: string

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      MONTH: ${{ inputs.month }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate month
        run: |
          if ! echo "$MONTH" | grep -Eq '^[0-9]{4}-[0-9]{2}$'; then
            echo "::error::Bad month format. Use YYYY-MM"; exit 1; fi
          echo "Month OK: $MONTH"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build Jira export
        run: python scripts/export_jira.py --month "$MONTH" --out export.csv

      - name: Upload export.csv
        uses: actions/upload-artifact@v4
        with:
          name: jira-export-${{ inputs.month }}
          path: export.csv
