name: Run Reopen Reports (export)

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Month YYYY-MM (e.g., 2025-08)"
        required: true
        type: string

permissions:
  contents: write   # <-- needed to push files

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}      # your secret name
      JIRA_EMAIL:     ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      MONTH:          ${{ inputs.month }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate month
        run: |
          if ! echo "$MONTH" | grep -Eq '^[0-9]{4}-[0-9]{2}$'; then
            echo "::error::Bad month format. Use YYYY-MM"; exit 1; fi
          echo "Month OK: $MONTH"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build Jira export
        run: python scripts/export_jira.py --month "$MONTH" --out export.csv

      - name: Save export into repo folder
        run: |
          mkdir -p exports/"$MONTH"
          mv -f export.csv exports/"$MONTH"/export.csv

      - name: Commit & push export
        uses: EndBug/add-and-commit@v9
        with:
          add: 'exports'
          message: "chore(reports): add export for ${{ inputs.month }}"
