name: Run Reopen Reports (export + python)

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Month YYYY-MM (e.g., 2025-08)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # map your secrets
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_EMAIL:     ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      MONTH:          ${{ inputs.month }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate month
        run: |
          if ! echo "$MONTH" | grep -Eq '^[0-9]{4}-[0-9]{2}$'; then
            echo "::error::Bad month format. Use YYYY-MM"; exit 1; fi
          echo "Month OK: $MONTH"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Build Jira export
        run: |
          python scripts/export_jira.py --month "$MONTH" --out export.csv

      - name: Preview export
        run: |
          echo "---- export.csv (first 10 lines) ----"
          head -n 10 export.csv || true
          echo "---- line count ----"
          wc -l export.csv || true

      - name: Run Python report generator
        run: |
          python scripts/run_reports_wrapper.py export.csv

      - name: Upload export.csv
        id: up_export
        uses: actions/upload-artifact@v4
        with:
          name: jira-export-${{ env.MONTH }}
          path: export.csv
          if-no-files-found: error

      - name: "Upload report - by user"
        id: up_user
        uses: actions/upload-artifact@v4
        with:
          name: reopen-report-by-user-${{ env.MONTH }}
          path: reports/reopens_by_user.csv
          if-no-files-found: error

      - name: "Upload report - by ticket"
        id: up_ticket
        uses: actions/upload-artifact@v4
        with:
          name: reopen-report-by-ticket-${{ env.MONTH }}
          path: reports/reopens_by_ticket.csv
          if-no-files-found: error

      - name: Add summary with links
        run: |
          {
            echo "## ✅ Reports ready"
            echo ""
            echo "**Month:** \`${MONTH}\`"
            echo ""
            echo "- Export:   https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${{ steps.up_export.outputs.artifact-id }}"
            echo "- By user:  https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${{ steps.up_user.outputs.artifact-id }}"
            echo "- By ticket:https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${{ steps.up_ticket.outputs.artifact-id }}"
            echo ""
            echo "_Or download from the **Artifacts** section at the bottom of this run._"
          } >> "$GITHUB_STEP_SUMMARY"
